### ISSUE TITLE
使用最新版的revanced-cli打包失败,似乎许多命令已改变

### ISSUE THREAD

**Issue by lgnb666** [kazutoiris/RoamingX-Mod#2]
原来的命令应该是
`java -jar revanced-cli.jar patch --merge integrations.apk --patch-bundle patches.jar --signing-levels 1,2,3 bilibili.apk`
我分别下载最新版的revanced-cli和你最新发布的两个文件并将其该名成上述命令中一样的前缀，但是运行失败，最新版的revanced-cli似乎命令发生了变化。

```
Missing required option: '--patches=<patchesFile>'
Usage: revanced-cli patch [-f] [--exclusive] [--mount] [--purge] [-i
                          [=<deviceSerial>]]
                          [--custom-aapt2-binary=<aaptBinaryPath>]
                          [--keystore=<keyStoreFilePath>]
                          [--keystore-entry-alias=<keyStoreEntryAlias>]
                          [--keystore-entry-password=<keyStoreEntryPassword>]
                          [--keystore-password=<keyStorePassword>]
                          [-o=<outputFilePath>] [--signer=<signer>]
                          [-t=<temporaryFilesPath>] -p=<patchesFile>
                          [-p=<patchesFile>]... [[[-O=<String=Object>]...
                          (-e=<name> | --ei=<index>)] [(-d=<name> |
                          --di=<index>)]]... <apk>
```
我需要使用旧版的revanced-cli吗?

**Comment by kazutoiris** [comment]
In the latest document, the command doesn’t appear to have changed. Perhaps there’s some misunderstanding.

https://github.com/zjns/revanced-cli/blob/d1a8e0d0e84942c39af027ddcf127f8e29643e6f/docs/1_usage.md?plain=1#L64-L71

**Comment by lgnb666** [comment]
> 在最新的文档中，该命令似乎没有改变。也许有什么误会。
> 
> [https://github.com/zjns/revanced-cli/blob/d1a8e0d0e84942c39af027ddcf127f8e29643e6f/docs/1_usage.md?plain=1#L64-L71 ](https://github.com/zjns/revanced-cli/blob/d1a8e0d0e84942c39af027ddcf127f8e29643e6f/docs/1_usage.md?plain=1#L64-L71)

抱歉，我下错地方了。我下载到了主分支的revanced-cli,我应该下载你上面提供的[revanced-cli](https://github.com/zjns/revanced-cli/releases/download/v4.6.0.1/revanced-cli.jar),你是正确的。

**Comment by kazutoiris** [comment]
Alright, I am now closing the issue. 😄

**Comment by lgnb666** [comment]
> Alright, I am now closing the issue. 😄
抱歉又打扰你了!😂
是这样的。
我使用下面命令打包最新版的Bilibili的过程中有关证书的步骤出了错误。
`java -jar revanced-cli.jar patch --merge integrations.apk --patch-bundle patches.jar --signing-levels 1,2,3 bilibili.apk`

错误如下：
```
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1192)
        at app.revanced.library.ApkSigner.newKeyStore(ApkSigner.kt:56)
        at app.revanced.library.ApkUtils.newPrivateKeyCertificatePair(ApkUtils.kt:114)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:168)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:331)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more
```
打包的bilibili版本(CN,google,HD)都无法安装成功，最后一步闪退，我的手机系统是华为鸿蒙4.2。
我不知道是我打包过程中证书导入失败造成的还是当前模块不适合最新版Bilibili？
所以又向你回复请求解答🙏。


我已经通过第三方软件重新签名，现在顺利安装，体验还行。

**Comment by lgnb666** [comment]
我用AppMirrorInstaller重新安装时看到了错误, 果然时证书的问题。

![Screenshot_20241125_005852_com apkmirror helper prod](https://github.com/user-attachments/assets/9e48f650-37fb-462a-83c5-c992d758c197)

我对java不是太熟悉,我只在我的计算机上安装了jdk21,所以我需要你的帮助，兄弟！

**Comment by kazutoiris** [comment]
Due to some reasons, JDK 21 hasn't been supported by `revanced-cli`.

https://github.com/zjns/revanced-cli/blob/d1a8e0d0e84942c39af027ddcf127f8e29643e6f/docs/0_prerequisites.md?plain=1#L7

**Comment by leij0318** [comment]
> Due to some reasons, JDK 21 hasn't been supported by `revanced-cli`.
> 
> https://github.com/zjns/revanced-cli/blob/d1a8e0d0e84942c39af027ddcf127f8e29643e6f/docs/0_prerequisites.md?plain=1#L7

所以我需要使用jdk11吗？我的计算机同时安装了jdk17和jdk21(Oracle JDK),我可以随时切换环境变量。或许我应该使用Open JDK。

**Comment by leij0318** [comment]
> > Due to some reasons, JDK 21 hasn't been supported by `revanced-cli`.
> > [zjns/revanced-cli@`d1a8e0d`/docs/0_prerequisites.md?plain=1#L7](https://github.com/zjns/revanced-cli/blob/d1a8e0d0e84942c39af027ddcf127f8e29643e6f/docs/0_prerequisites.md?plain=1#L7)
> 
> 所以我需要使用 jdk11 吗？我的计算机同时安装了 jdk17 和 jdk21 (Oracle JDK), 我可以随时切换环境变量。或许我应该使用 Open JDK。

我又重新安装了open JDK17,打包少了很多错误，但是会员画质解锁和强解码信息报错。虽然没有签名和证书报错，但我在安装时还是显示没有证书。最后我通过MT管理器签名打包好的APK才成功安装。
